<a href="https://colab.research.google.com/github/imanshgupta/text-sentiment-analysis/blob/main/Spam_NonSpam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk;
from nltk.tokenize import RegexpTokenizer, word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
dataframe=pd.read_csv('/content/drive/MyDrive/spam.csv',encoding='ISO-8859-1')
le=LabelEncoder();

In [ ]:
data=dataframe.to_numpy()
print(data[0])
print(data[2])

['ham'
 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 nan nan nan]
['spam'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 nan nan nan]


In [ ]:
X=data[:,1]#data in the 1st col ie the message
y=data[:,0]#data in the second column ie the spam/non-spam

In [ ]:
tokenizer=RegexpTokenizer('\w+')
stop_words=set(stopwords.words('english'))
ps=PorterStemmer()

In [ ]:
def rem_words_and_stem(data):
  data=data.lower()
  words=tokenizer.tokenize(data)
  removed_stopwords=[w for w in words if w not in stop_words]
  stemmed_words=[ps.stem(w) for w in removed_stopwords]
  clean_text=' '.join(stemmed_words)
  return clean_text

In [ ]:
def cleandata(document):
  d=[]
  for i in document:
    d.append(rem_words_and_stem(i))
  return d

In [ ]:
cleandocument=cleandata(X)
print(cleandocument[:10])

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat', 'ok lar joke wif u oni', 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18', 'u dun say earli hor u c alreadi say', 'nah think goe usf live around though', 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send å 1 50 rcv', 'even brother like speak treat like aid patent', 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun', 'winner valu network custom select receivea å 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour', 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030']


In [ ]:
cv=CountVectorizer()

In [ ]:
#create the library of our words from the training set
vc=cv.fit_transform(cleandocument)
print(vc)
print(cv.vocabulary_)#set of our vocabulary that we have created from our data set

  (0, 3037)	1
  (0, 3704)	1
  (0, 4998)	1
  (0, 2044)	1
  (0, 1215)	1
  (0, 1595)	1
  (0, 3115)	1
  (0, 7043)	1
  (0, 3812)	1
  (0, 1593)	1
  (0, 1832)	1
  (0, 3077)	1
  (0, 1028)	1
  (0, 6868)	1
  (1, 4657)	1
  (1, 3843)	1
  (1, 3671)	1
  (1, 6966)	1
  (1, 4682)	1
  (2, 2876)	1
  (2, 2545)	2
  (2, 7009)	1
  (2, 1929)	1
  (2, 6977)	1
  (2, 2665)	2
  :	:
  (5567, 4584)	1
  (5568, 3037)	1
  (5568, 3329)	1
  (5568, 7199)	1
  (5568, 2865)	1
  (5568, 2577)	1
  (5569, 6131)	1
  (5569, 4333)	1
  (5569, 4940)	1
  (5570, 2876)	1
  (5570, 6902)	1
  (5570, 3922)	1
  (5570, 4506)	1
  (5570, 6706)	1
  (5570, 5878)	1
  (5570, 1621)	1
  (5570, 2503)	1
  (5570, 2966)	1
  (5570, 3159)	1
  (5570, 3541)	1
  (5570, 890)	1
  (5570, 1420)	1
  (5571, 4427)	1
  (5571, 6553)	1
  (5571, 5437)	1
{'go': 3037, 'jurong': 3704, 'point': 4998, 'crazi': 2044, 'avail': 1215, 'bugi': 1595, 'great': 3115, 'world': 7043, 'la': 3812, 'buffet': 1593, 'cine': 1832, 'got': 3077, 'amor': 1028, 'wat': 6868, 'ok': 4657, 'lar': 3

In [ ]:
X=vc.todense()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
train_test_split?

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [ ]:
#pregiven naive bayes from sk learn
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.977705274605764

In [ ]:
messages=["Hi this is Ansh and Sahana. Hope this mail finds you in good health","Please verify your account by clicking on the verify button or link to continue accessing the platform.Important : If your e-mail is not verified within 7 days, your Mettl Contests account will be deactivated.You can log into Mettl Contests using your e-mail address.If you have any questions or concerns, please don't hesitate to contact us mettl-support@mercer.com",
          "Hello Everyone. Hope you are doing well. We are conducting a quick survey on Power crisis as part of the Design Thinking Lab.Please spare a few minutes to fill out the form. Thank you for your time in advance!!Power Crisis SurveyScarcity of Electricity and reduce the dependence on nonrenewable resources such as fossil fuels and production of eco friendly energy",
          "Please find the registration link belowis 30th aug 2021, 2PM.Elevate and GenC categories.Regards,Anusha M SPC-MCA Dept RVCE 97397752 Attention: BE all branches, M.Tech all branches and MCA Cognizant is recruiting our students for two  categories, GenC Elevate and Gen"
]

In [ ]:
def preparetestdata(message):
  d=cleandata(message)
  return cv.transform(d)

clean_test_message=preparetestdata(messages)

In [ ]:
result=model.predict(clean_test_message)
print(result)

['ham' 'spam' 'ham' 'spam']
